---
  - name: Change hostname to skipper
    win_hostname:
      name: skipper

  - name: Install Active Directory Services
    win_feature: >
      name=AD-Domain-Services
      include_management_tools=yes
      include_sub_features=yes
      state=present

  - name: Promote skipper to domain controller
    win_domain:
      create_dns_delegation: no
      dns_domain_name: waddlecorp.local
      domain_netbios_name: WADDLECORP
      safe_mode_password: PassW0rd432!
    register: domain_install

  - name: Reboot after promotion and wait for "Applying computer settings" to finish
    win_reboot:
      test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'
      post_reboot_delay: 200
    when: domain_install.reboot_required

  - name: Set DA user account information
    win_domain_user:
      name: skipper
      firstname: Skipper
      password: PassW0rd432!
      state: present
      groups:
        - Domain Admins

  - include: accounts.yml

