---
- hosts: private
  gather_facts: True
  vars:
    ansible_winrm_transport: plaintext
    ansible_winrm_scheme: http
    waddlecorp_domain_hostname: "private"
    ethernet_adapter: "Ethernet 2"
    anpt_flag: "flag4.txt"
  tasks:
  - name: Activate windows
    win_shell: cscript slmgr.vbs /rearm
    args:
      chdir: C:\Windows\System32\
  roles:
    - role: private
    - role: placeflag
    - role: joindomain
