---
- hosts: tien
  gather_facts: False
  vars:
    ansible_winrm_transport: plaintext
    ansible_winrm_scheme: http
    waddlecorp_domain_hostname: "tien"
    ethernet_adapter: "Local Area Connection 2"
    ansible_user: vagrant
    ansible_password: vagrant
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    anpt_flag: "flag2.txt"
  roles:
    - role: joindomain
    - role: placeflag
