- hosts: skipper
  gather_facts: True
  vars:
    dc_address: 172.28.128.100
    dc_netmask_cidr: 24
    dc_gateway: 172.28.128.2
    dc_hostname: skipper
    domain_Name: waddlecorp.local
    ansible_winrm_transport: plaintext
    ansible_winrm_scheme: http
  tasks:
  - name: Set a static address to 172.28.128.100
    win_shell: "(new-netipaddress -InterfaceAlias \"Ethernet 2\" -IPAddress {{ dc_address }} -prefixlength {{dc_netmask_cidr}} -defaultgateway {{ dc_gateway }})"

  - name: Change hostname to skipper
    win_hostname:
      name: skipper

  - name: Install Active Directory Services
    win_feature: >
      name=AD-Domain-Services
      include_management_tools=yes
      include_sub_features=yes
      state=present

  - name: Promote skipper to domain controller
    win_domain:
      create_dns_delegation: no
      dns_domain_name: waddlecorp.local
      domain_netbios_name: WADDLECORP
      safe_mode_password: PassW0rd432!
    register: domain_install

  - name: Set DA user account information
    win_domain_user:
      name: skipper
      firstname: Skipper
      password: PassW0rd432!
      state: present
      groups:
        - Domain Admins

  - name: Reboot after promotion
    raw: shutdown /r
